create table action_log
(
    id             integer generated by default as identity
        constraint action_log_pk
            primary key,
    user_id        integer                                not null
        constraint action_log_users_user_id_fk
            references users,
    action_type    varchar(256)                           not null,
    created_at     timestamp with time zone default now() not null,
    action_details jsonb
);

alter table action_log
    owner to postgres;

