create table conversation_participants
(
    id              integer generated by default as identity
        primary key,
    user_id         integer
        constraint public_conversation_participants_user_id_fkey
            references users,
    conversation_id integer
        constraint public_conversation_participants_conversation_id_fkey
            references conversation
);

alter table conversation_participants
    owner to postgres;

