create table conversation_participant
(
    id              integer generated by default as identity
        primary key,
    user_id         integer
        constraint public_conversation_participant_user_id_fkey
            references users,
    conversation_id integer
        constraint public_conversation_participant_conversation_id_fkey
            references conversation
);

alter table conversation_participant
    owner to postgres;

