create table conversation
(
    conversation_id integer generated by default as identity
        primary key,
    type            varchar(256),
    last_action_at  timestamp with time zone
);

alter table conversation
    owner to postgres;

