create table message
(
    message_id      integer generated by default as identity
        primary key,
    conversation_id integer                                not null
        constraint public_message_conversation_id_fkey
            references conversation,
    sent_at         timestamp with time zone default now() not null,
    sent_by         integer                                not null,
    type            varchar(256)                           not null,
    value           varchar(1000)                          not null
);

alter table message
    owner to postgres;


