create table product_subcategory
(
    product_subcategory_id integer generated by default as identity
        constraint product_subcategory_pk
            primary key,
    product_category_id    integer      not null
        constraint product_subcategory_product_category_product_category_id_fk
            references product_category,
    value                  varchar(256) not null
);

alter table product_subcategory
    owner to postgres;

