create table product_like
(
    id                 integer generated by default as identity
        constraint product_like_pk
            primary key,
    user_id            integer not null
        constraint product_like_users_user_id_fk
            references users,
    product_id         integer not null
        constraint product_like_product_product_id_fk
            references product,
    status             varchar(256),
    last_update_action timestamp with time zone default now()
);

alter table product_like
    owner to postgres;

