create table product_specification
(
    specification_id integer generated by default as identity
        constraint product_specification_pk
            primary key,
    product_id       integer      not null
        constraint product_specification_product_product_id_fk
            references product,
    key              varchar(255) not null,
    value            varchar(255) not null
);

alter table product_specification
    owner to postgres;

