create table product
(
    product_id  integer generated by default as identity
        constraint product_pk
            primary key,
    user_id     integer                                not null
        constraint product_users_user_id_fk
            references users,
    created_at  timestamp with time zone default now() not null,
    title       varchar(255)                           not null,
    description varchar(2000),
    price       double precision,
    category_id integer                                not null
        constraint product_product_category_product_category_id_fk
            references product_category,
    popularity  integer                                not null
);

alter table product
    owner to postgres;

