create table product_category
(
    product_category_id integer generated by default as identity
        constraint product_category_pk
            primary key,
    value               varchar(256) not null,
    parent_id           integer
        constraint product_category_product_category_product_category_id_fk
            references product_category
);

alter table product_category
    owner to postgres;

