create table registration_code
(
    id         integer generated by default as identity,
    email      varchar(256) not null,
    code       varchar(256) not null,
    created_at timestamp with time zone default now()
);

alter table registration_code
    owner to postgres;

