create table security_code
(
    id         integer generated by default as identity
        constraint security_code_pk
            primary key,
    email      varchar(256),
    code       varchar(256) not null,
    created_at timestamp with time zone default now(),
    code_type  varchar(256) not null
);

alter table security_code
    owner to postgres;

